name: documentation

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.DOCUMENTATION_BUILD_ENABLED }} == 'true' ]; then
            echo "ok=enabled" >> $GITHUB_OUTPUT
          fi
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Config npm registry token
        run: npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          npm install --legacy-peer-deps
          git clone https://github.com/etherealengine/etherealengine-docs.git docs
          cd docs
          cp .env.local.default .env.local
          npm install --legacy-peer-deps
          npm run build
  gh-release:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Config github npm registry token
        run: npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to GitHub Pages
        timeout-minutes: 200
        env:
          NODE_OPTIONS: --max_old_space_size=16384
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          npm install --legacy-peer-deps
          git clone https://github.com/etherealengine/etherealengine-docs.git docs
          cd docs
          cp .env.local.default .env.local
          npm install --legacy-peer-deps
          npm run deploy
